name: Pull request checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-labeler:
    uses: adup-tech/devops_git-workflows/.github/workflows/_run_labeler.yml@main
  commit-lint:
    uses: adup-tech/devops_git-workflows/.github/workflows/_run_commit_lint.yml@main
  pr-title-lint:
    uses: adup-tech/devops_git-workflows/.github/workflows/_run_pr_linter.yml@main
