name: Workflow Sync

on:
  push:
    branches:
      - master
env:
  DRY_RUN: true
  REPOSITORIES: |
    adup-tech/devops_salt-adup

  WORKFLOW_FILES: |
    pull-request.yml
jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}